config/routes.rb
Rails.application.routes.draw do
 
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "authors#index"

  resources :authors do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :comments
    validates :first_name, presence: true,length:{minimum:3}
    validates :last_name, presence: true,length:{minimum:2}
    validates :dob, presence: true 
    validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
end

app/models/authorsbook.rb
class Authorsbook < ApplicationRecord
  belongs_to :author
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/models/bookname.rb
class Bookname < ApplicationRecord
  belongs_to :author
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
        def index
          @authors = Author.all
        end
      
        def show
          @author = Author.find(params[:id])
        end
      
        def new
          @author = Author.new
        end
      
        def create
          @author = Author.new(author_params)
      
          if @author.save
            redirect_to @author
          else
            render :new, status: :unprocessable_entity
          end
        end
      
        def edit
          @author = Author.find(params[:id])
        end
      
        def update
          @author= Author.find(params[:id])
      
          if @author.update(author_params)
            redirect_to @author
          else
            render :edit, status: :unprocessable_entity
          end
        end
      
        def destroy
          @author = Author.find(params[:id])
          @author.destroy
      
          redirect_to root_path, status: :see_other
        end
      
        private
          def author_params
            params.require(:author).permit(:first_name, :last_name, :dob, :email)
          end
      end
      
  
  
  

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @author = Author.find(params[:author_id])
        @comment = @author.comments.create(comment_params)
        redirect_to author_path(@author)
      end
    
      private
        def comment_params
          params.require(:comment).permit(:commenter, :body)
        end
    end
    Copy
    
end

app/helpers/add_column_to_authors_helper.rb
module AddColumnToAuthorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/add_column_to_authors/age:integer.html.erb
<h1>AddColumnToAuthors#age:integer</h1>
<p>Find me in app/views/add_column_to_authors/age:integer.html.erb</p>

app/views/authors/_form.html.erb
<%= form_with model: author do |form| %>
    <div>
      <%= form.label :first_name %><br>
      <%= form.text_field :first_name %>
    </div>
  
    <div>
      <%= form.label :last_name %><br>
      <%= form.text_area :last_name %>
    </div>
    
    <div>
    <%= form.label :dob %><br>
     <%= form.text_area :dob %>
   </div>

    <div>
     <%= form.label :email %><br>
     <%= form.text_area :email %>
    </div>
  
   
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

  

app/views/authors/edit.html.erb
<h1>Edit Author</h1>

<%= render "form", author: @author %>

app/views/authors/index.html.erb
<h1>Authors</h1>

<ul>
  <% @authors.each do |authors| %>
    <li>
      <%= link_to authors.first_name, authors %>
    </li>
  <% end %>
</ul>
<%= link_to "New Author", new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= form_with model: @author do |form| %>
  <div>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name %><br>
    <%= form.text_area :last_name %>
  </div>
  
  <div>
   <%= form.label :dob %><br>
   <%= form.text_area :dob %>
 </div>

  <div>
   <%= form.label :email %><br>
   <%= form.text_area :email %>
  </div>

  

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/show.html.erb
<h1><%= @author.first_name %></h1>

<h1><%= @author.last_name %></h1>

<h1><%= @author.dob %></h1>

<h1><%= @author.email %></h1>



<ul>
  <li><%= link_to "Edit", edit_author_path(@author) %></li>
  <li><%= link_to "Destroy", author_path(@author), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<h2>Add a comment:</h2>
<%= form_with model: [ @author, @author.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
  <% end %>

  <h2>Add a comment:</h2>
<%= form_with model: [ @author, @author.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practical</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>